apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-code-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-code-demo
  template:
    metadata:
      labels:
        app: cloud-code-demo
    spec:
      containers:
      - name: cloud-code-demo
        image: eu.gcr.io/altfatterz/cloud-code-demo
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-code-demo
spec:
  type: LoadBalancer
  selector:
    app: cloud-code-demo
  ports:
  - protocol: TCP
    # port is from the host, targetPort inside the container
    port: 8080
    targetPort: 8080