apiVersion: v1
kind: Service
metadata:
  name: cloud-code-demo
spec:
  type: LoadBalancer
  selector:
    app: cloud-code-demo
  ports:
  - protocol: TCP
    # port is from the host, targetPort inside the container
    port: 8080
    targetPort: 8080
